<?php

namespace Tests\Feature\app\Http\Controller\Api;

use App\Jobs\SendCreatedUserMailJob;
use App\Models\Organization;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\Queue;
use Tests\TestCase;

class OrganizationControllerTest extends TestCase
{
    use WithFaker, RefreshDatabase;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Organization::factory()->create();
        $this->user = User::factory()->create();
        $this->actingAs($this->user);
    }

    public function test_it_should_be_able_to_create_a_new_user_that_belongs_to_the_organization(): void
    {
        // arrange
        Queue::fake();

        $payload = [
            'name' => $this->faker->name,
            'email' => $this->faker->unique()->email(),
        ];

        // act
        $response = $this->postJson(route('organizations.users.store'), $payload);

        // assert
        $response->assertStatus(201);
        $this->assertDatabaseHas('users', [
            'id' => 2,
            'organization_id' => 1,
            'email_verified_at' => null,
        ]);

        Queue::assertPushed(SendCreatedUserMailJob::class);
    }
}
